### ISSUE TITLE
Feature Request: Raised Hand(s)

### ISSUE THREAD

**Issue by sysdef** [RealKeyboardWarrior/zoomer#3]
* A list of participants who has the hand raised 🤚.
* An event when someone raise or lower the hand.

**Comment by RealKeyboardWarrior** [comment]
Hi,

That sounds like an easy to add feature!


## Receive raise hands updates from everyone

Event sent to everyone:
```json
{"body":{"add":null,"remove":null,"update":[{"bRaiseHand":true,"id":16778240}]},"evt":7937,"seq":105}
```

The way to add this would be:
1.  Check if the `evt` with value `7937 ` is in [the constants files](https://github.com/RealKeyboardWarrior/zoomer/blob/main/zoom/consts.go#L126) which is  already being processed  because this is the generic way that Zoom updates the conference roster.
2. Update the "update" section in `ConferenceRosterIndication` - [here](https://github.com/RealKeyboardWarrior/zoomer/blob/main/zoom/message_types.go#L64) to have the `BRaiseHand` property so it can decode it from the JSON 👍 
3. If you take the example, you should now have these updates available here; https://github.com/RealKeyboardWarrior/zoomer/blob/main/examples/record-video/videorecoder.go#L53-L64 

## Raise hands
```json
{"evt":4131,"body":{"bOn":true,"id":16778240},"seq":26}
``` 

1.  Check if the `evt`  number (`4131`) is available in the [constant file](https://github.com/RealKeyboardWarrior/zoomer/blob/main/zoom/consts.go#L67) which it is!
2. Add a "RaiseHandIndication" [here](https://github.com/RealKeyboardWarrior/zoomer/blob/main/zoom/consts.go#L165-L168)
3. Add something like "RaiseHand" in requests file, you can use this as a base: https://github.com/RealKeyboardWarrior/zoomer/blob/main/zoom/requests.go#L116-L126

**Comment by RealKeyboardWarrior** [comment]
@sysdef I've added an example as well here 
https://github.com/RealKeyboardWarrior/zoomer/blob/main/examples/raise-hands/main.go
